In [1]:
import pandas as pd

In [3]:
carros = [7, 4, 3, 2, 8]
dias = pd.date_range(start='20190101', end='20190101', periods=5)
vendedor = ['Geroge', 'Vagner', 'Pedro', 'Vagner', 'Geroge']
df = pd.DataFrame({'Vendas': carros, 'Data': dias, 'Vendedor': vendedor})

In [4]:
df

   Vendas       Data Vendedor
0       7 2019-01-01   Geroge
1       4 2019-01-01   Vagner
2       3 2019-01-01    Pedro
3       2 2019-01-01   Vagner
4       8 2019-01-01   Geroge

In [12]:
from pandas.core.reshape.pivot import AggFuncType
pd.pivot_table(df, index='Data', columns='Vendedor', values='Vendas', aggfunc='sum')

Vendedor    Geroge  Pedro  Vagner
Data
2019-01-01      15      3       6